/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ammFactorySol from "./AmmFactory.sol";
export type { ammFactorySol };
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
export type { AMM } from "./AMM";
